version: "3.9"
services:
  client:
    build: ./frontend
    container_name: MyWebFrontend_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  server:
    build: ./backend
    container_name: MyWebBackend_c
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
